# Generated by Django 5.2 on 2025-04-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.BooleanField(default=True),
        ),
    ]
