# Generated by Django 5.2 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_customer_height_customer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='custopymer',
        ),
    ]
