# Generated by Django 5.2 on 2025-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customer_height_alter_customer_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
