# Generated by Django 5.2 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_customer_height_alter_customer_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='malefemale', max_length=10),
        ),
    ]
